spring.application.name=olx-advertise

spring.datasource.url=jdbc:mysql://localhost:3306/olxadvertise
spring.datasource.username=root
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

