spring.application.name=olx-advertise

spring.datasource.url=jdbc:mysql://localhost:3306/olxadvertise
spring.datasource.username=root
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# OLX Login service base URL (for token validation)
olx.login.service.url=http://localhost:8081

# OLX Masterdata service base URL (for category and status lookups)
olx.masterdata.service.url=http://localhost:8082


# Enable Feign fallbacks via Spring Cloud CircuitBreaker
feign.circuitbreaker.enabled=true
